name: DoNothing

on: [push, workflow_dispatch] 

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: Do Nothing
      run: |
        echo "Hello world!"
