name: DoNothingWindows

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: [windows]
    steps:
    - uses: actions/checkout@v3
    - name: Do Nothing Windows
      run: |
        echo "Hello World!"
