name: DoNothingWindows

on: [push]

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v3
    - name: Do Nothing Windows
      run: |
        echo "Hello world!"
